spring:
  application:
    name: st-zuul-server
#  cloud:
#    config:
#      uri: http://localhost:5000

server:
  port: 5003
  
zuul:
  routes:
    robot-on-mars:
      url: http://31.220.55.236:8090
    st-product:
      path: /st-product/api/**
      serviceId: st-product              
  
eureka:
  instance:
    hostname: 31.220.55.236
    port: 5002
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000 